version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=itpl
    ports:
      - 3306:3306
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'itpl'
      MYSQL_USER: 'itpl'
      MYSQL_PASSWORD: 'itpl'
      MYSQL_ROOT_PASSWORD: 'itpl'
    volumes:
      - ./data:/var/lib/mysql
volumes:
  data: